export const FILL_IMPORT = "FILL_IMPORT"
export const EDIT_TEMPLATE = "EDIT_TEMPLATE"
export const GENERATE_TABLE = "GENERATE_TABLE"
export const KEYWORD_CHANGE = "KEYWORD_CHANGE"
export const REMARK_WORD = "REMARK_WORD"
export const COLOR_PHRASE = "COLOR_PHRASE"
export const FILL_EXPORT = "FILL_EXPORT"
export const DELETE_EXPORT = "DELETE_EXPORT"
export const REVERSE_KEYWORD = "REVERSE_KEYWORD"

export const MAX_LENGTH = 35;